name: pytest
on: push
env:
  CC_TEST_REPORTER_ID: c6cd69f90890f01df38e825c681b699de7f0761e48b9de27a5b1aeaf5d17c484
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip install pytest
          pip install pytest-cov
      - uses: paambaati/codeclimate-action@v3.0.0
        services:
          - postgresql
        install:
          - pip install -r requirements_common.txt
          - npm install
        before_script:
          - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          - chmod +x ./cc-test-reporter
          - ./cc-test-reporter before-build
        script:
          - pytest --cov-report term-missing --cov=gendiff
        after_script:
          - pytest --cov-report xml:cov.xml
          - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

#      - name: Test
#        run: |
#          pytest --cov-report term-missing --cov=gendiff
#          pytest --cov-report xml:cov.xml

#        run: |
#          coverage run -m pytest
#          coverage xml
#      - uses: paambaati/codeclimate-action@v3.0.0
#        env:
#          CC_TEST_REPORTER_ID: c6cd69f90890f01df38e825c681b699de7f0761e48b9de27a5b1aeaf5d17c484
#        with:
#          coverageLocations: |
#            ${{github.workspace}}/coverage.xml:coverage.py

