name: pytest
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip install pytest
          pip install pytest-cov

      - uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: c6cd69f90890f01df38e825c681b699de7f0761e48b9de27a5b1aeaf5d17c484
        with:
          coverageCommand: pytest --cov-report term --cov=gendiff
#      - name: Run pytest
#        run: pytest --cov-report term --cov==gendiff