name: pytest
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip install pytest
          pip install pytest-cov
      - name: Create Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Test
        run: |
          pytest --cov=gendiff tests/ --cov-report xml
      - name: Sending Reporter
        run: |
          ./cc-test-reporter after-build -r c6cd69f90890f01df38e825c681b699de7f0761e48b9de27a5b1aeaf5d17c484

